name: Build and Release Linux Binaries

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
        type: string

env:
  GO_VERSION: '1.21'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
    
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Download dependencies
      run: go mod tidy && go mod download
    
    - name: Build Linux binary
      env:
        GOOS: linux
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 1
      run: |
        # Install cross-compilation tools for ARM64
        if [ "$GOARCH" = "arm64" ]; then
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
          export CC=aarch64-linux-gnu-gcc
        fi
        
        # Build binary
        BINARY_NAME="go-server-linux-${{ matrix.goarch }}"
        go build -ldflags="-s -w" -o ${BINARY_NAME} main.go
        
        # Create checksum for the binary
        sha256sum "${BINARY_NAME}" > "${BINARY_NAME}.sha256"
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: go-server-linux-${{ matrix.goarch }}
        path: |
          go-server-linux-${{ matrix.goarch }}
          go-server-linux-${{ matrix.goarch }}.sha256

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag != ''
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create and push tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag -a "${{ github.event.inputs.tag }}" -m "Release ${{ github.event.inputs.tag }}"
        git push origin "${{ github.event.inputs.tag }}"
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts
    
    - name: Prepare release files
      run: |
        mkdir -p release
        find ./artifacts -name "go-server-linux-*" -not -name "*.sha256" -exec cp {} ./release/ \;
        find ./artifacts -name "*.sha256" -exec cp {} ./release/ \;
        ls -la ./release/
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.tag }}
        name: Release ${{ github.event.inputs.tag }}
        files: |
          release/go-server-linux-amd64
          release/go-server-linux-amd64.sha256
          release/go-server-linux-arm64
          release/go-server-linux-arm64.sha256
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
